### ISSUE TITLE
z drift?

### ISSUE THREAD

**Issue by maomao0220** [iDonghq/FAST_LIO_LOCALIZATION_PLUS#5]
how to add the constraint of ground to fix z drift?

**Comment by arjunskumar** [comment]
@maomao0220        [L1287](https://github.com/iDonghq/FAST_LIO_LOCALIZATION_PLUS/blob/24f01af0f5f7de84321e1ee0475117c86c16ee17/src/laserMapping.cpp#L1287) please look at this

**Comment by maomao0220** [comment]
thanks
